Version with AlertDialog in WorkInProgress fragment. Almost finished.
Bug to fix:

java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.com.mastersatwork.mastersatwork/ru.com.mastersatwork.mastersatwork.MainActivity}: java.lang.IllegalStateException: Fragment no longer exists for key android:target_state: index 1